### ISSUE TITLE
Cannot get real time data being always zero despite good communication according debug logs

### ISSUE THREAD

**Issue by matbe81** [Kubiac/homebridge-solaredge-realtime#4]
**Describe The Bug:**
Real time value is always 0 lux

**To Reproduce:**
Nothing special.

**Expected behavior:**
Having the real time data correct as it look to be a calculation issue.

**Logs:**

```
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Connecting to Inverter real-time at 192.168.0.17
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Connected
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Received Power:  [ 10198 ]
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Interpreted power value:  -55338
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Received SF:  [ 65535 ]
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Computed: -5533.8
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] Updating Ambient Light Level:  0.0001
[4/13/2022, 5:21:32 PM] [SolaredgeRealTime] closed connection to 192.168.0.17
```

**Plugin Config:**

```json
{
    "name": "SolaredgeRealTime",
    "inverter": [
        {
            "id": "Inverter-realtime",
            "displayName": "Inverter real-time",
            "ip": "192.168.0.17",
            "port": 1502,
            "updateInterval": 5,
            "powerAddress": 40083,
            "powerSfAddress": 40084,
            "powerUnsignedValue": false
        }
    ],
    "platform": "SolaredgeRealTime"
}
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/8006424/163219420-34f19100-2f54-4c60-9176-c3d8bdae4ed5.png)

**Environment:**

* **Plugin Version**:

    OS: Ubuntu 20.04.4 LTS (HassIO under vmware VM)
    Software: 1.4.0
    Node: 16.14.2
    npm: 8.6.0

**Comment by matbe81** [comment]
You are right. It works. 
But instructions seems not correct so:
![image](https://user-images.githubusercontent.com/8006424/172196557-6849e4a3-6ba2-4625-a542-35c88ef093af.png)

**Comment by Kalie15** [comment]
in your json.config it's now

"powerUnsignedValue": true

and that is the truth ;-)

**Comment by matbe81** [comment]
Correct. Updating the GUI for clarity can be appreciated.

**Comment by Kubiac** [comment]
Starting with version 0.11 the plugin can display two light meters when values are signed (can be negative). So you can now monitor import and export. I will adapt the UI for more clarity.

Thanks for the feedback

**Comment by Kubiac** [comment]
Check out version 0.13
